config/routes.rb
Rails.application.routes.draw do
  root 'user_mentions#index'
  get '/search', to: "user_mentions#search"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_mention.rb
class UserMention
  include Mongoid::Document
  field :username, type: String
  field :mentions, type: Hash
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/user_mentions_controller.rb
class UserMentionsController < ApplicationController
  before_action :set_user_mention, only: [:show, :edit, :update, :destroy]

  # GET /user_mentions
  # GET /user_mentions.json
  def index
    @user_mentions = UserMention.all
  end

  # GET /user_mentions/1
  # GET /user_mentions/1.json
  def show
  end

  # GET /user_mentions/new
  def new
    @user_mention = UserMention.new
  end

  # GET /user_mentions/1/edit
  def edit
  end

  def search
    @username = params[:q]
    @mentions = Array.new
    @count = 0
    (1..5).each do |i|
      begin
        @tweets = $client.user_timeline(@username, options={:count => 200, :page => i})
      rescue Twitter::Error::NotFound
        @error = "User not found."
      rescue Twitter::Error::TooManyRequests
        @error = "You've made too many requests, but we have a cached version of your results."
        begin
          @cached_um = UserMention.find_by(username: @username)
        rescue Mongoid::Errors::DocumentNotFound
          @error = "You've made too many requests. Unfortunately, we have no cached data for the username entered."
        else 
          @sorted_mc = @cached_um.mentions
        end
      else 
        @tweets.each do |tweet|
          @count += 1
          tweet.user_mentions.each do |mention|
            if mention.attrs[:screen_name].downcase != @username.downcase
              @mentions.push('@' + mention.attrs[:screen_name])
            end
          end
        end
      end
    end
    if @mentions.length != 0
      @mentions_count = Hash.new(0)
      @mentions.each { |mention| @mentions_count[mention] += 1 }
      @sorted_mc = Hash[@mentions_count.sort_by{ |_, v| -v }]
    else
      if !@error 
        @error = "No mentions found."
      end
    end
    begin
      @params = { :username => @username, :mentions => @sorted_mc }
      @um = UserMention.new(@params)
      @um.save
    rescue Mongo::Error::OperationFailure => e
      @cached_um = UserMention.find_by(username: @username)
      @cached_um.mentions = @sorted_mc
      @cached_um.save
    end
  end

  # POST /user_mentions
  # POST /user_mentions.json
  def create
    @user_mention = UserMention.new(user_mention_params)

    respond_to do |format|
      if @user_mention.save
        format.html { redirect_to @user_mention, notice: 'User mention was successfully created.' }
        format.json { render :show, status: :created, location: @user_mention }
      else
        format.html { render :new }
        format.json { render json: @user_mention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_mentions/1
  # PATCH/PUT /user_mentions/1.json
  def update
    respond_to do |format|
      if @user_mention.update(user_mention_params)
        format.html { redirect_to @user_mention, notice: 'User mention was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_mention }
      else
        format.html { render :edit }
        format.json { render json: @user_mention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_mentions/1
  # DELETE /user_mentions/1.json
  def destroy
    @user_mention.destroy
    respond_to do |format|
      format.html { redirect_to user_mentions_url, notice: 'User mention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_mention
      @user_mention = UserMention.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_mention_params
      params.require(:user_mention).permit(:username, :mentions)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_mentions_helper.rb
module UserMentionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_mentions/_form.html.erb
<%= form_for(user_mention) do |f| %>
  <% if user_mention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_mention.errors.count, "error") %> prohibited this user_mention from being saved:</h2>

      <ul>
      <% user_mention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :mentions %>
    <%= f.text_field :mentions %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_mentions/edit.html.erb
<h1>Editing User Mention</h1>

<%= render 'form', user_mention: @user_mention %>

<%= link_to 'Show', @user_mention %> |
<%= link_to 'Back', user_mentions_path %>

app/views/user_mentions/index.html.erb
<% @title="The Mentionator" %>

<head>
  <title><%= @title %></title>
</head>

<div class="col-md-8">
<p id="notice"><%= notice %></p>

<h1>The Mentionator</h1>
<h6>Having <a href="https://www.youtube.com/watch?v=J-f2L2_UkfY&feature=youtu.be&t=19s">nightmares about your Twitter mentions?</a> Check 'em out with the Mentionator!</h6>
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Enter username:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>
</div>

app/views/user_mentions/new.html.erb
<h1>New User Mention</h1>

<%= render 'form', user_mention: @user_mention %>

<%= link_to 'Back', user_mentions_path %>

app/views/user_mentions/search.html.erb
<% @title="Mentions" %>

<head>
  <title>Mentions</title>
</head>


<div class="col-md-8">
<h1>Mentions</h1>

<p><%= @error %></p>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search again?") %>
  <br>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<br> <br>

<% if @sorted_mc %>
<table>
	<th>
		<tr>
			<td><h5>Username</h5></td>
			<td><h5>Count</h5></td>
		</tr>
	</th>
<% @sorted_mc.each do |mc, count| %>
	<tr>
		<td><%= mc %></td>
		<td><%= count %></td>
	</tr>
	<% end %>
	</table>
	<br>
<% end %>
<% end %>
</div>

app/views/user_mentions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user_mention.username %>
</p>

<p>
  <strong>Mentions:</strong>
  <%= @user_mention.mentions %>
</p>

<%= link_to 'Edit', edit_user_mention_path(@user_mention) %> |
<%= link_to 'Back', user_mentions_path %>